### PR TITLE
chore: add youtube channel to navigation & footer links

### PR DESCRIPTION
**Pull request by bsmth**
__Background:__
We should add a link to the YouTube channel where we have been uploading webinars.

### CODE REVIEW

**Comment by bsmth** [comment]
Q: Does it make more sense under Resources?

**Comment by mpsq** [comment]
I would move the link to "resources", IMO, "community" is for content that has a social aspect, where people can interact with us.

**Comment by bsmth** [comment]
Thanks, that was my gut feeling - I think it's more appropriate as  __Resources -> Videos__

**Review by mpsq — APPROVED** [review]
lgtm

**Pull request merged**
