### PR TITLE
light theme code preview

### PR DESCRIPTION
**Pull request by argshook**
This PR implements light theme for code blocks. The colours are similar
to code highlighting on GitHub.

This is related to #684 (light theme for tables), these PRs should probably be merged together.

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks for the changes, I like it. Please note that the Java syntax highlighting is broken, though. Maybe we can fix it in this PR? 

> these PRs should probably be merged together.

Sounds good.

**Comment by argshook** [comment]
> Thanks for the changes, I like it. Please note that the Java syntax highlighting is broken, though. Maybe we can fix it in this PR?

i extracted your comment into an issue here https://github.com/questdb/questdb.io/issues/687

i'd like to do a separate PR with a fix for that, if you don't mind

**Comment by bsmth** [comment]
> i'd like to do a separate PR with a fix for that, if you don't mind

Let's do it that way 👍🏻

**Review by bsmth — APPROVED** [review]
Thanks!

**Pull request merged**
