### PR TITLE
chore(ui): update 404 page

### PR DESCRIPTION
**Pull request by argshook**
This PR updates 404 page with few simple changes:

- display the URL that was not found
- update text
- show the search box
- add a few links to other QuestDB resources

# before:
image

# after

### CODE REVIEW

**Comment by bluestreak01** [comment]
I'm unsure about the UX:

image

The "search" box suggest it is an input, but when you click it - it is a well disguised button. It should looks unambiguously a button.

**Comment by argshook** [comment]
> I'm unsure about the UX:
> 
> image
> 
> The "search" box suggest it is an input, but when you click it - it is a well disguised button. It should looks unambiguously a button.

i agree, however i'm merely reusing existing functionality of our search integration with algolia.

I could (probably) make something nicer but it would take longer.

wdyt, should i pursue?

**Comment by argshook** [comment]
@bluestreak01 i re-read your comment but understood it this time. I'll update the PR and will ping you once i'm done

**Comment by argshook** [comment]
@bluestreak01 i updated the UI a bit, would be nice if you could double check. Thank you!

example URL: https://deploy-preview-1315--unruffled-blackwell-31bfb2.netlify.app/uh%20oh%20page%20not%20found

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
