### PR TITLE
image overflow at swag page

### PR DESCRIPTION
**Pull request by saikrishnatbijil**
what i did is changed the default size of the image to `300px` and at `min-width: 800px` i changed it to `400px`
**before:**
Screen Shot 2023-04-19 at 10 28 39 PM
**after:**
Screen Shot 2023-04-19 at 10 28 57 PM

### CODE REVIEW

**Review by argshook — CHANGES_REQUESTED** [review]
unable to merge, because this change affects the layout on wider screens.

**Comment by saikrishnatbijil** [comment]
> unable to merge, because this change affects the layout on wider screens.
i checked it and it looks normal in wider screens 
Screen Shot 2023-04-20 at 4 43 37 PM

**Comment by argshook** [comment]
It looks normal as in it's not broken. But it looks different from our current view. We would prefer fixes for narrow screens to not affect the UI of wider screens.

Hope that makes sense!

**Comment by saikrishnatbijil** [comment]
@argshook i think i fixed it now

**Comment by argshook** [comment]
> @argshook i think i fixed it now

sorry, i still see an issue.
Please compare wide screen on the preview of this PR against current production version:

# production

Screenshot 2023-04-21 at 10 33 04

# this PR

Screenshot 2023-04-21 at 10 33 14

The layout is different: production version has bigger picture, which has impact on the width of text.

It's not a huge change, but if we're doing a fix, it should not have regressions.

**Comment by saikrishnatbijil** [comment]
@argshook i don't know why this is happening but i tested it, Here is my screen while i was testing it,
So for convenience i toggled light mode on the local website, and dark mode in the production 
https://user-images.githubusercontent.com/98866798/233587269-51036dba-0aab-46ab-ae28-15d056b86f39.mov

**Review by argshook — APPROVED** [review]

**Pull request merged**
