### PR TITLE
Fix several grammar issues and typos in questBb.io docs

### PR DESCRIPTION
**Pull request by wanderer163**

### CODE REVIEW

**Comment by amyshwang** [comment]
Thank you @wanderer163. Please could you sign the agreement mentioned [here](https://github.com/questdb/questdb.io/pull/1143#issuecomment-1285915149) so that we could proceed with this PR?

**Comment by wanderer163** [comment]
> Thank you @wanderer163. Please could you sign the agreement mentioned [here](https://github.com/questdb/questdb.io/pull/1143#issuecomment-1285915149) so that we could proceed with this PR?

I have signed it, but the status isn't reflecting. Would you know why? I have clicked on the "recheck" CLA status button as well.

**Comment by argshook** [comment]
> > Thank you @wanderer163. Please could you sign the agreement mentioned [here](https://github.com/questdb/questdb.io/pull/1143#issuecomment-1285915149) so that we could proceed with this PR?
> 
> I have signed it, but the status isn't reflecting. Would you know why? I have clicked on the "recheck" CLA status button as well.

Hey there, @wanderer163 Thanks for contributing!

Please double check that you're logged in to the same `wanderer163` GitHub
username when signing the CLA.

The CLA assistant seem to work well, and i remember this happened to me
in the past, so wanted to double check with you. Thanks!

**Comment by wanderer163** [comment]
> > > Thank you @wanderer163. Please could you sign the agreement mentioned [here](https://github.com/questdb/questdb.io/pull/1143#issuecomment-1285915149) so that we could proceed with this PR?
> > 
> > 
> > I have signed it, but the status isn't reflecting. Would you know why? I have clicked on the "recheck" CLA status button as well.
> 
> Hey there, @wanderer163 Thanks for contributing!
> 
> Please double check that you're logged in to the same `wanderer163` GitHub username when signing the CLA.
> 
> The CLA assistant seem to work well, and i remember this happened to me in the past, so wanted to double check with you. Thanks!

Signed 👍

**Review by argshook — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
