### PR TITLE
ui update added search button on smaller screens

### PR DESCRIPTION
**Pull request by saikrishnatbijil**
So now mobile phone users cannot search on the website. I have added the search feature on mobile.
**Search feature added Screenshots:**
Screen Shot 2023-04-16 at 4 01 07 PM
Screen Shot 2023-04-16 at 4 01 30 PM

### CODE REVIEW

**Comment by amyshwang** [comment]
@saikrishnatbijil Thank you for the PRs you have contributed in the past few days. Our team will review them. However, for future contributions, please keep in mind that we encourage more thorough and/or automated fixes that address more than one location.

We will close future contributions if a PR does not meet our expectations.
Thank you for your understanding.

**Comment by saikrishnatbijil** [comment]
Ok but didn't quite understand what you meant by more thorough and/or automated. Could you please explain

**Comment by amyshwang** [comment]
@saikrishnatbijil essentially we would encourage contributors to combine a few small PRs into a bigger one if they are addressing similar problems. 
We appreciate the fixes but combining PRs in a more systematic way could help our small team review them :)

**Comment by saikrishnatbijil** [comment]
Ok, got it

**Comment by saikrishnatbijil** [comment]
@argshook should i close this pull request.

**Comment by amyshwang** [comment]
PR closed as the issue was fixed by #1566

**Pull request closed without merging**
