### PR TITLE
docs: a typo fix

### PR DESCRIPTION
**Pull request by saintmalik**
made correction to a typo i found

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Great, thanks @saintmalik 🙌🏻

**Comment by saintmalik** [comment]
> Great, thanks @saintmalik 🙌🏻

do you permit contribution under /tutorial/ folder ?

**Comment by bsmth** [comment]
> do you permit contribution under /tutorial/ folder ?

Yes absolutely, please see the convention for the existing tutorials, but you are very welcome to submit an addition!

**Comment by saintmalik** [comment]
> > do you permit contribution under /tutorial/ folder ?
> 
> Yes absolutely, please see the convention for the existing tutorials, but you are very welcome to submit an addition!

Okay thanks

**Pull request merged**
